[build]
  command = "chmod a+x ./build.sh && ./build.sh"
  functions = "functions"
  publish = "public"

[build.environment]
  GO_IMPORT_PATH = "github.com/carlmjohnson/netlify-go-function-demo"
  GO111MODULE = "on"

