ALTER TABLE `address` MODIFY COLUMN `id` serial AUTO_INCREMENT NOT NULL;
ALTER TABLE `address` MODIFY COLUMN `user_id` varchar(32) NOT NULL;
ALTER TABLE `address` MODIFY COLUMN `country` varchar(64) NOT NULL;
ALTER TABLE `address` MODIFY COLUMN `state` varchar(64) NOT NULL;
ALTER TABLE `address` MODIFY COLUMN `street` varchar(64) NOT NULL;
ALTER TABLE `address` MODIFY COLUMN `second_street` varchar(64) NOT NULL;
ALTER TABLE `address` MODIFY COLUMN `apartment_number` varchar(10) NOT NULL;
ALTER TABLE `address` MODIFY COLUMN `postal_code` varchar(10) NOT NULL;
ALTER TABLE `address` MODIFY COLUMN `contact_number` varchar(20) NOT NULL;
ALTER TABLE `address` MODIFY COLUMN `is_default` boolean NOT NULL;
ALTER TABLE `session` MODIFY COLUMN `created_at` timestamp DEFAULT NOW();
ALTER TABLE `user_activity` MODIFY COLUMN `created_at` timestamp DEFAULT NOW();
ALTER TABLE `user_profile` MODIFY COLUMN `created_at` timestamp DEFAULT NOW();
ALTER TABLE `user_profile` MODIFY COLUMN `dob` timestamp NOT NULL;
ALTER TABLE `address` ADD `dial_code` varchar(10) NOT NULL;
ALTER TABLE `address` ADD `additional_information` varchar(128);