const countries = [
  {
    id: 1,
    code: 'AF',
    name: 'Afghanistan',
    dialCode: '93',
  },
  {
    id: 2,
    code: 'AX',
    name: 'Aland Islands',
    dialCode: '358',
  },
  {
    id: 3,
    code: 'AL',
    name: 'Albania',
    dialCode: '355',
  },
  {
    id: 4,
    code: 'DZ',
    name: 'Algeria',
    dialCode: '213',
  },
  {
    id: 5,
    code: 'AS',
    name: 'American Samoa',
    dialCode: '1684',
  },
  {
    id: 6,
    code: 'AD',
    name: 'Andorra',
    dialCode: '376',
  },
  {
    id: 7,
    code: 'AO',
    name: 'Angola',
    dialCode: '244',
  },
  {
    id: 8,
    code: 'AI',
    name: 'Anguilla',
    dialCode: '1264',
  },
  {
    id: 9,
    code: 'AQ',
    name: 'Antarctica',
    dialCode: '672',
  },
  {
    id: 10,
    code: 'AG',
    name: 'Antigua and Barbuda',
    dialCode: '1268',
  },
  {
    id: 11,
    code: 'AR',
    name: 'Argentina',
    dialCode: '54',
  },
  {
    id: 12,
    code: 'AM',
    name: 'Armenia',
    dialCode: '374',
  },
  {
    id: 13,
    code: 'AW',
    name: 'Aruba',
    dialCode: '297',
  },
  {
    id: 14,
    code: 'AU',
    name: 'Australia',
    dialCode: '61',
  },
  {
    id: 15,
    code: 'AT',
    name: 'Austria',
    dialCode: '43',
  },
  {
    id: 16,
    code: 'AZ',
    name: 'Azerbaijan',
    dialCode: '994',
  },
  {
    id: 17,
    code: 'BS',
    name: 'Bahamas',
    dialCode: '1242',
  },
  {
    id: 18,
    code: 'BH',
    name: 'Bahrain',
    dialCode: '973',
  },
  {
    id: 19,
    code: 'BD',
    name: 'Bangladesh',
    dialCode: '880',
  },
  {
    id: 20,
    code: 'BB',
    name: 'Barbados',
    dialCode: '1246',
  },
  {
    id: 21,
    code: 'BY',
    name: 'Belarus',
    dialCode: '375',
  },
  {
    id: 22,
    code: 'BE',
    name: 'Belgium',
    dialCode: '32',
  },
  {
    id: 23,
    code: 'BZ',
    name: 'Belize',
    dialCode: '501',
  },
  {
    id: 24,
    code: 'BJ',
    name: 'Benin',
    dialCode: '229',
  },
  {
    id: 25,
    code: 'BM',
    name: 'Bermuda',
    dialCode: '1441',
  },
  {
    id: 26,
    code: 'BT',
    name: 'Bhutan',
    dialCode: '975',
  },
  {
    id: 27,
    code: 'BO',
    name: 'Bolivia',
    dialCode: '591',
  },
  {
    id: 28,
    code: 'BQ',
    name: 'Bonaire, Sint Eustatius and Saba',
    dialCode: '599',
  },
  {
    id: 29,
    code: 'BA',
    name: 'Bosnia and Herzegovina',
    dialCode: '387',
  },
  {
    id: 30,
    code: 'BW',
    name: 'Botswana',
    dialCode: '267',
  },
  {
    id: 31,
    code: 'BV',
    name: 'Bouvet Island',
    dialCode: '55',
  },
  {
    id: 32,
    code: 'BR',
    name: 'Brazil',
    dialCode: '55',
  },
  {
    id: 33,
    code: 'IO',
    name: 'British Indian Ocean Territory',
    dialCode: '246',
  },
  {
    id: 34,
    code: 'BN',
    name: 'Brunei Darussalam',
    dialCode: '673',
  },
  {
    id: 35,
    code: 'BG',
    name: 'Bulgaria',
    dialCode: '359',
  },
  {
    id: 36,
    code: 'BF',
    name: 'Burkina Faso',
    dialCode: '226',
  },
  {
    id: 37,
    code: 'BI',
    name: 'Burundi',
    dialCode: '257',
  },
  {
    id: 38,
    code: 'KH',
    name: 'Cambodia',
    dialCode: '855',
  },
  {
    id: 39,
    code: 'CM',
    name: 'Cameroon',
    dialCode: '237',
  },
  {
    id: 40,
    code: 'CA',
    name: 'Canada',
    dialCode: '1',
  },
  {
    id: 41,
    code: 'CV',
    name: 'Cape Verde',
    dialCode: '238',
  },
  {
    id: 42,
    code: 'KY',
    name: 'Cayman Islands',
    dialCode: '1345',
  },
  {
    id: 43,
    code: 'CF',
    name: 'Central African Republic',
    dialCode: '236',
  },
  {
    id: 44,
    code: 'TD',
    name: 'Chad',
    dialCode: '235',
  },
  {
    id: 45,
    code: 'CL',
    name: 'Chile',
    dialCode: '56',
  },
  {
    id: 46,
    code: 'CN',
    name: 'China',
    dialCode: '86',
  },
  {
    id: 47,
    code: 'CX',
    name: 'Christmas Island',
    dialCode: '61',
  },
  {
    id: 48,
    code: 'CC',
    name: 'Cocos (Keeling) Islands',
    dialCode: '672',
  },
  {
    id: 49,
    code: 'CO',
    name: 'Colombia',
    dialCode: '57',
  },
  {
    id: 50,
    code: 'KM',
    name: 'Comoros',
    dialCode: '269',
  },
  {
    id: 51,
    code: 'CG',
    name: 'Congo',
    dialCode: '242',
  },
  {
    id: 52,
    code: 'CD',
    name: 'Congo, Democratic Republic of the Congo',
    dialCode: '242',
  },
  {
    id: 53,
    code: 'CK',
    name: 'Cook Islands',
    dialCode: '682',
  },
  {
    id: 54,
    code: 'CR',
    name: 'Costa Rica',
    dialCode: '506',
  },
  {
    id: 55,
    code: 'CI',
    name: "Cote D'Ivoire",
    dialCode: '225',
  },
  {
    id: 56,
    code: 'HR',
    name: 'Croatia',
    dialCode: '385',
  },
  {
    id: 57,
    code: 'CU',
    name: 'Cuba',
    dialCode: '53',
  },
  {
    id: 58,
    code: 'CW',
    name: 'Curacao',
    dialCode: '599',
  },
  {
    id: 59,
    code: 'CY',
    name: 'Cyprus',
    dialCode: '357',
  },
  {
    id: 60,
    code: 'CZ',
    name: 'Czech Republic',
    dialCode: '420',
  },
  {
    id: 61,
    code: 'DK',
    name: 'Denmark',
    dialCode: '45',
  },
  {
    id: 62,
    code: 'DJ',
    name: 'Djibouti',
    dialCode: '253',
  },
  {
    id: 63,
    code: 'DM',
    name: 'Dominica',
    dialCode: '1767',
  },
  {
    id: 64,
    code: 'DO',
    name: 'Dominican Republic',
    dialCode: '1809',
  },
  {
    id: 65,
    code: 'EC',
    name: 'Ecuador',
    dialCode: '593',
  },
  {
    id: 66,
    code: 'EG',
    name: 'Egypt',
    dialCode: '20',
  },
  {
    id: 67,
    code: 'SV',
    name: 'El Salvador',
    dialCode: '503',
  },
  {
    id: 68,
    code: 'GQ',
    name: 'Equatorial Guinea',
    dialCode: '240',
  },
  {
    id: 69,
    code: 'ER',
    name: 'Eritrea',
    dialCode: '291',
  },
  {
    id: 70,
    code: 'EE',
    name: 'Estonia',
    dialCode: '372',
  },
  {
    id: 71,
    code: 'ET',
    name: 'Ethiopia',
    dialCode: '251',
  },
  {
    id: 72,
    code: 'FK',
    name: 'Falkland Islands (Malvinas)',
    dialCode: '500',
  },
  {
    id: 73,
    code: 'FO',
    name: 'Faroe Islands',
    dialCode: '298',
  },
  {
    id: 74,
    code: 'FJ',
    name: 'Fiji',
    dialCode: '679',
  },
  {
    id: 75,
    code: 'FI',
    name: 'Finland',
    dialCode: '358',
  },
  {
    id: 76,
    code: 'FR',
    name: 'France',
    dialCode: '33',
  },
  {
    id: 77,
    code: 'GF',
    name: 'French Guiana',
    dialCode: '594',
  },
  {
    id: 78,
    code: 'PF',
    name: 'French Polynesia',
    dialCode: '689',
  },
  {
    id: 79,
    code: 'TF',
    name: 'French Southern Territories',
    dialCode: '262',
  },
  {
    id: 80,
    code: 'GA',
    name: 'Gabon',
    dialCode: '241',
  },
  {
    id: 81,
    code: 'GM',
    name: 'Gambia',
    dialCode: '220',
  },
  {
    id: 82,
    code: 'GE',
    name: 'Georgia',
    dialCode: '995',
  },
  {
    id: 83,
    code: 'DE',
    name: 'Germany',
    dialCode: '49',
  },
  {
    id: 84,
    code: 'GH',
    name: 'Ghana',
    dialCode: '233',
  },
  {
    id: 85,
    code: 'GI',
    name: 'Gibraltar',
    dialCode: '350',
  },
  {
    id: 86,
    code: 'GR',
    name: 'Greece',
    dialCode: '30',
  },
  {
    id: 87,
    code: 'GL',
    name: 'Greenland',
    dialCode: '299',
  },
  {
    id: 88,
    code: 'GD',
    name: 'Grenada',
    dialCode: '1473',
  },
  {
    id: 89,
    code: 'GP',
    name: 'Guadeloupe',
    dialCode: '590',
  },
  {
    id: 90,
    code: 'GU',
    name: 'Guam',
    dialCode: '1671',
  },
  {
    id: 91,
    code: 'GT',
    name: 'Guatemala',
    dialCode: '502',
  },
  {
    id: 92,
    code: 'GG',
    name: 'Guernsey',
    dialCode: '44',
  },
  {
    id: 93,
    code: 'GN',
    name: 'Guinea',
    dialCode: '224',
  },
  {
    id: 94,
    code: 'GW',
    name: 'Guinea-Bissau',
    dialCode: '245',
  },
  {
    id: 95,
    code: 'GY',
    name: 'Guyana',
    dialCode: '592',
  },
  {
    id: 96,
    code: 'HT',
    name: 'Haiti',
    dialCode: '509',
  },
  {
    id: 97,
    code: 'HM',
    name: 'Heard Island and Mcdonald Islands',
    dialCode: '0',
  },
  {
    id: 98,
    code: 'VA',
    name: 'Holy See (Vatican City State)',
    dialCode: '39',
  },
  {
    id: 99,
    code: 'HN',
    name: 'Honduras',
    dialCode: '504',
  },
  {
    id: 100,
    code: 'HK',
    name: 'Hong Kong',
    dialCode: '852',
  },
  {
    id: 101,
    code: 'HU',
    name: 'Hungary',
    dialCode: '36',
  },
  {
    id: 102,
    code: 'IS',
    name: 'Iceland',
    dialCode: '354',
  },
  {
    id: 103,
    code: 'IN',
    name: 'India',
    dialCode: '91',
  },
  {
    id: 104,
    code: 'ID',
    name: 'Indonesia',
    dialCode: '62',
  },
  {
    id: 105,
    code: 'IR',
    name: 'Iran, Islamic Republic of',
    dialCode: '98',
  },
  {
    id: 106,
    code: 'IQ',
    name: 'Iraq',
    dialCode: '964',
  },
  {
    id: 107,
    code: 'IE',
    name: 'Ireland',
    dialCode: '353',
  },
  {
    id: 108,
    code: 'IM',
    name: 'Isle of Man',
    dialCode: '44',
  },
  {
    id: 109,
    code: 'IL',
    name: 'Israel',
    dialCode: '972',
  },
  {
    id: 110,
    code: 'IT',
    name: 'Italy',
    dialCode: '39',
  },
  {
    id: 111,
    code: 'JM',
    name: 'Jamaica',
    dialCode: '1876',
  },
  {
    id: 112,
    code: 'JP',
    name: 'Japan',
    dialCode: '81',
  },
  {
    id: 113,
    code: 'JE',
    name: 'Jersey',
    dialCode: '44',
  },
  {
    id: 114,
    code: 'JO',
    name: 'Jordan',
    dialCode: '962',
  },
  {
    id: 115,
    code: 'KZ',
    name: 'Kazakhstan',
    dialCode: '7',
  },
  {
    id: 116,
    code: 'KE',
    name: 'Kenya',
    dialCode: '254',
  },
  {
    id: 117,
    code: 'KI',
    name: 'Kiribati',
    dialCode: '686',
  },
  {
    id: 118,
    code: 'KP',
    name: "Korea, Democratic People's Republic of",
    dialCode: '850',
  },
  {
    id: 119,
    code: 'KR',
    name: 'Korea, Republic of',
    dialCode: '82',
  },
  {
    id: 120,
    code: 'XK',
    name: 'Kosovo',
    dialCode: '381',
  },
  {
    id: 121,
    code: 'KW',
    name: 'Kuwait',
    dialCode: '965',
  },
  {
    id: 122,
    code: 'KG',
    name: 'Kyrgyzstan',
    dialCode: '996',
  },
  {
    id: 123,
    code: 'LA',
    name: "Lao People's Democratic Republic",
    dialCode: '856',
  },
  {
    id: 124,
    code: 'LV',
    name: 'Latvia',
    dialCode: '371',
  },
  {
    id: 125,
    code: 'LB',
    name: 'Lebanon',
    dialCode: '961',
  },
  {
    id: 126,
    code: 'LS',
    name: 'Lesotho',
    dialCode: '266',
  },
  {
    id: 127,
    code: 'LR',
    name: 'Liberia',
    dialCode: '231',
  },
  {
    id: 128,
    code: 'LY',
    name: 'Libyan Arab Jamahiriya',
    dialCode: '218',
  },
  {
    id: 129,
    code: 'LI',
    name: 'Liechtenstein',
    dialCode: '423',
  },
  {
    id: 130,
    code: 'LT',
    name: 'Lithuania',
    dialCode: '370',
  },
  {
    id: 131,
    code: 'LU',
    name: 'Luxembourg',
    dialCode: '352',
  },
  {
    id: 132,
    code: 'MO',
    name: 'Macao',
    dialCode: '853',
  },
  {
    id: 133,
    code: 'MK',
    name: 'Macedonia, the Former Yugoslav Republic of',
    dialCode: '389',
  },
  {
    id: 134,
    code: 'MG',
    name: 'Madagascar',
    dialCode: '261',
  },
  {
    id: 135,
    code: 'MW',
    name: 'Malawi',
    dialCode: '265',
  },
  {
    id: 136,
    code: 'MY',
    name: 'Malaysia',
    dialCode: '60',
  },
  {
    id: 137,
    code: 'MV',
    name: 'Maldives',
    dialCode: '960',
  },
  {
    id: 138,
    code: 'ML',
    name: 'Mali',
    dialCode: '223',
  },
  {
    id: 139,
    code: 'MT',
    name: 'Malta',
    dialCode: '356',
  },
  {
    id: 140,
    code: 'MH',
    name: 'Marshall Islands',
    dialCode: '692',
  },
  {
    id: 141,
    code: 'MQ',
    name: 'Martinique',
    dialCode: '596',
  },
  {
    id: 142,
    code: 'MR',
    name: 'Mauritania',
    dialCode: '222',
  },
  {
    id: 143,
    code: 'MU',
    name: 'Mauritius',
    dialCode: '230',
  },
  {
    id: 144,
    code: 'YT',
    name: 'Mayotte',
    dialCode: '262',
  },
  {
    id: 145,
    code: 'MX',
    name: 'Mexico',
    dialCode: '52',
  },
  {
    id: 146,
    code: 'FM',
    name: 'Micronesia, Federated States of',
    dialCode: '691',
  },
  {
    id: 147,
    code: 'MD',
    name: 'Moldova, Republic of',
    dialCode: '373',
  },
  {
    id: 148,
    code: 'MC',
    name: 'Monaco',
    dialCode: '377',
  },
  {
    id: 149,
    code: 'MN',
    name: 'Mongolia',
    dialCode: '976',
  },
  {
    id: 150,
    code: 'ME',
    name: 'Montenegro',
    dialCode: '382',
  },
  {
    id: 151,
    code: 'MS',
    name: 'Montserrat',
    dialCode: '1664',
  },
  {
    id: 152,
    code: 'MA',
    name: 'Morocco',
    dialCode: '212',
  },
  {
    id: 153,
    code: 'MZ',
    name: 'Mozambique',
    dialCode: '258',
  },
  {
    id: 154,
    code: 'MM',
    name: 'Myanmar',
    dialCode: '95',
  },
  {
    id: 155,
    code: 'NA',
    name: 'Namibia',
    dialCode: '264',
  },
  {
    id: 156,
    code: 'NR',
    name: 'Nauru',
    dialCode: '674',
  },
  {
    id: 157,
    code: 'NP',
    name: 'Nepal',
    dialCode: '977',
  },
  {
    id: 158,
    code: 'NL',
    name: 'Netherlands',
    dialCode: '31',
  },
  {
    id: 159,
    code: 'AN',
    name: 'Netherlands Antilles',
    dialCode: '599',
  },
  {
    id: 160,
    code: 'NC',
    name: 'New Caledonia',
    dialCode: '687',
  },
  {
    id: 161,
    code: 'NZ',
    name: 'New Zealand',
    dialCode: '64',
  },
  {
    id: 162,
    code: 'NI',
    name: 'Nicaragua',
    dialCode: '505',
  },
  {
    id: 163,
    code: 'NE',
    name: 'Niger',
    dialCode: '227',
  },
  {
    id: 164,
    code: 'NG',
    name: 'Nigeria',
    dialCode: '234',
  },
  {
    id: 165,
    code: 'NU',
    name: 'Niue',
    dialCode: '683',
  },
  {
    id: 166,
    code: 'NF',
    name: 'Norfolk Island',
    dialCode: '672',
  },
  {
    id: 167,
    code: 'MP',
    name: 'Northern Mariana Islands',
    dialCode: '1670',
  },
  {
    id: 168,
    code: 'NO',
    name: 'Norway',
    dialCode: '47',
  },
  {
    id: 169,
    code: 'OM',
    name: 'Oman',
    dialCode: '968',
  },
  {
    id: 170,
    code: 'PK',
    name: 'Pakistan',
    dialCode: '92',
  },
  {
    id: 171,
    code: 'PW',
    name: 'Palau',
    dialCode: '680',
  },
  {
    id: 172,
    code: 'PS',
    name: 'Palestinian Territory, Occupied',
    dialCode: '970',
  },
  {
    id: 173,
    code: 'PA',
    name: 'Panama',
    dialCode: '507',
  },
  {
    id: 174,
    code: 'PG',
    name: 'Papua New Guinea',
    dialCode: '675',
  },
  {
    id: 175,
    code: 'PY',
    name: 'Paraguay',
    dialCode: '595',
  },
  {
    id: 176,
    code: 'PE',
    name: 'Peru',
    dialCode: '51',
  },
  {
    id: 177,
    code: 'PH',
    name: 'Philippines',
    dialCode: '63',
  },
  {
    id: 178,
    code: 'PN',
    name: 'Pitcairn',
    dialCode: '64',
  },
  {
    id: 179,
    code: 'PL',
    name: 'Poland',
    dialCode: '48',
  },
  {
    id: 180,
    code: 'PT',
    name: 'Portugal',
    dialCode: '351',
  },
  {
    id: 181,
    code: 'PR',
    name: 'Puerto Rico',
    dialCode: '1787',
  },
  {
    id: 182,
    code: 'QA',
    name: 'Qatar',
    dialCode: '974',
  },
  {
    id: 183,
    code: 'RE',
    name: 'Reunion',
    dialCode: '262',
  },
  {
    id: 184,
    code: 'RO',
    name: 'Romania',
    dialCode: '40',
  },
  {
    id: 185,
    code: 'RU',
    name: 'Russian Federation',
    dialCode: '70',
  },
  {
    id: 186,
    code: 'RW',
    name: 'Rwanda',
    dialCode: '250',
  },
  {
    id: 187,
    code: 'BL',
    name: 'Saint Barthelemy',
    dialCode: '590',
  },
  {
    id: 188,
    code: 'SH',
    name: 'Saint Helena',
    dialCode: '290',
  },
  {
    id: 189,
    code: 'KN',
    name: 'Saint Kitts and Nevis',
    dialCode: '1869',
  },
  {
    id: 190,
    code: 'LC',
    name: 'Saint Lucia',
    dialCode: '1758',
  },
  {
    id: 191,
    code: 'MF',
    name: 'Saint Martin',
    dialCode: '590',
  },
  {
    id: 192,
    code: 'PM',
    name: 'Saint Pierre and Miquelon',
    dialCode: '508',
  },
  {
    id: 193,
    code: 'VC',
    name: 'Saint Vincent and the Grenadines',
    dialCode: '1784',
  },
  {
    id: 194,
    code: 'WS',
    name: 'Samoa',
    dialCode: '684',
  },
  {
    id: 195,
    code: 'SM',
    name: 'San Marino',
    dialCode: '378',
  },
  {
    id: 196,
    code: 'ST',
    name: 'Sao Tome and Principe',
    dialCode: '239',
  },
  {
    id: 197,
    code: 'SA',
    name: 'Saudi Arabia',
    dialCode: '966',
  },
  {
    id: 198,
    code: 'SN',
    name: 'Senegal',
    dialCode: '221',
  },
  {
    id: 199,
    code: 'RS',
    name: 'Serbia',
    dialCode: '381',
  },
  {
    id: 200,
    code: 'CS',
    name: 'Serbia and Montenegro',
    dialCode: '381',
  },
  {
    id: 201,
    code: 'SC',
    name: 'Seychelles',
    dialCode: '248',
  },
  {
    id: 202,
    code: 'SL',
    name: 'Sierra Leone',
    dialCode: '232',
  },
  {
    id: 203,
    code: 'SG',
    name: 'Singapore',
    dialCode: '65',
  },
  {
    id: 204,
    code: 'SX',
    name: 'Sint Maarten',
    dialCode: '1',
  },
  {
    id: 205,
    code: 'SK',
    name: 'Slovakia',
    dialCode: '421',
  },
  {
    id: 206,
    code: 'SI',
    name: 'Slovenia',
    dialCode: '386',
  },
  {
    id: 207,
    code: 'SB',
    name: 'Solomon Islands',
    dialCode: '677',
  },
  {
    id: 208,
    code: 'SO',
    name: 'Somalia',
    dialCode: '252',
  },
  {
    id: 209,
    code: 'ZA',
    name: 'South Africa',
    dialCode: '27',
  },
  {
    id: 210,
    code: 'GS',
    name: 'South Georgia and the South Sandwich Islands',
    dialCode: '500',
  },
  {
    id: 211,
    code: 'SS',
    name: 'South Sudan',
    dialCode: '211',
  },
  {
    id: 212,
    code: 'ES',
    name: 'Spain',
    dialCode: '34',
  },
  {
    id: 213,
    code: 'LK',
    name: 'Sri Lanka',
    dialCode: '94',
  },
  {
    id: 214,
    code: 'SD',
    name: 'Sudan',
    dialCode: '249',
  },
  {
    id: 215,
    code: 'SR',
    name: 'Suriname',
    dialCode: '597',
  },
  {
    id: 216,
    code: 'SJ',
    name: 'Svalbard and Jan Mayen',
    dialCode: '47',
  },
  {
    id: 217,
    code: 'SZ',
    name: 'Swaziland',
    dialCode: '268',
  },
  {
    id: 218,
    code: 'SE',
    name: 'Sweden',
    dialCode: '46',
  },
  {
    id: 219,
    code: 'CH',
    name: 'Switzerland',
    dialCode: '41',
  },
  {
    id: 220,
    code: 'SY',
    name: 'Syrian Arab Republic',
    dialCode: '963',
  },
  {
    id: 221,
    code: 'TW',
    name: 'Taiwan, Province of China',
    dialCode: '886',
  },
  {
    id: 222,
    code: 'TJ',
    name: 'Tajikistan',
    dialCode: '992',
  },
  {
    id: 223,
    code: 'TZ',
    name: 'Tanzania, United Republic of',
    dialCode: '255',
  },
  {
    id: 224,
    code: 'TH',
    name: 'Thailand',
    dialCode: '66',
  },
  {
    id: 225,
    code: 'TL',
    name: 'Timor-Leste',
    dialCode: '670',
  },
  {
    id: 226,
    code: 'TG',
    name: 'Togo',
    dialCode: '228',
  },
  {
    id: 227,
    code: 'TK',
    name: 'Tokelau',
    dialCode: '690',
  },
  {
    id: 228,
    code: 'TO',
    name: 'Tonga',
    dialCode: '676',
  },
  {
    id: 229,
    code: 'TT',
    name: 'Trinidad and Tobago',
    dialCode: '1868',
  },
  {
    id: 230,
    code: 'TN',
    name: 'Tunisia',
    dialCode: '216',
  },
  {
    id: 231,
    code: 'TR',
    name: 'Turkey',
    dialCode: '90',
  },
  {
    id: 232,
    code: 'TM',
    name: 'Turkmenistan',
    dialCode: '7370',
  },
  {
    id: 233,
    code: 'TC',
    name: 'Turks and Caicos Islands',
    dialCode: '1649',
  },
  {
    id: 234,
    code: 'TV',
    name: 'Tuvalu',
    dialCode: '688',
  },
  {
    id: 235,
    code: 'UG',
    name: 'Uganda',
    dialCode: '256',
  },
  {
    id: 236,
    code: 'UA',
    name: 'Ukraine',
    dialCode: '380',
  },
  {
    id: 237,
    code: 'AE',
    name: 'United Arab Emirates',
    dialCode: '971',
  },
  {
    id: 238,
    code: 'GB',
    name: 'United Kingdom',
    dialCode: '44',
  },
  {
    id: 239,
    code: 'US',
    name: 'United States',
    dialCode: '1',
  },
  {
    id: 240,
    code: 'UM',
    name: 'United States Minor Outlying Islands',
    dialCode: '1',
  },
  {
    id: 241,
    code: 'UY',
    name: 'Uruguay',
    dialCode: '598',
  },
  {
    id: 242,
    code: 'UZ',
    name: 'Uzbekistan',
    dialCode: '998',
  },
  {
    id: 243,
    code: 'VU',
    name: 'Vanuatu',
    dialCode: '678',
  },
  {
    id: 244,
    code: 'VE',
    name: 'Venezuela',
    dialCode: '58',
  },
  {
    id: 245,
    code: 'VN',
    name: 'Viet Nam',
    dialCode: '84',
  },
  {
    id: 246,
    code: 'VG',
    name: 'Virgin Islands, British',
    dialCode: '1284',
  },
  {
    id: 247,
    code: 'VI',
    name: 'Virgin Islands, U.s.',
    dialCode: '1340',
  },
  {
    id: 248,
    code: 'WF',
    name: 'Wallis and Futuna',
    dialCode: '681',
  },
  {
    id: 249,
    code: 'EH',
    name: 'Western Sahara',
    dialCode: '212',
  },
  {
    id: 250,
    code: 'YE',
    name: 'Yemen',
    dialCode: '967',
  },
  {
    id: 251,
    code: 'ZM',
    name: 'Zambia',
    dialCode: '260',
  },
  {
    id: 252,
    code: 'ZW',
    name: 'Zimbabwe',
    dialCode: '263',
  },
] as const;
export type Country = (typeof countries)[number];

export const countryMapping = countries.reduce((acc, country) => {
  acc[country.code] = country;
  return acc;
}, {} as Record<Country['code'], (typeof countries)[number]>);

export default countries;
